// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	TOKEN_KEY: string;
	SALT: string;
	GOOGLE_ID: string;
	GOOGLE_SECRET: string;
	GITHUB_ID: string;
	GITHUB_SECRET: string;
	JWT_SECRET: string;
	DB: D1Database;
}
